### ISSUE TITLE
Failed image import

### ISSUE THREAD

**Issue by jmslbam** [pixline/wp-cli-theme-test-command#14]
I ran `wp theme-test install` got this:

```
Failed to import Media &#8220;test-image-landscape-900&#8221;<br />Failed to import Media &#8220;test-image-portrait&#8221;<br />-- Added post_meta _wp_attachment_image_alt
```

Then this

```
-- Added post_meta _wp_attachment_image_alt
-- Added post_meta _attachment_original_parent_id
-- Added post_meta _wp_attachment_image_alt
-- Added post_meta _wp_attachment_image_alt
-- Added post_meta _attachment_original_parent_id
```

Then another

```
Failed to import Media &#8220;dsc20050727_091048_222&#8221;<br />Failed to import Media &#8220;dsc20050813_115856_52&#8221;<br />Failed to import Media &#8220;dsc20050831_165238_332&#8221;<br />Failed to import Media &#8220;dsc20050901_105100_212&#8221;<br />-- Added post_meta _wp_attachment_image_alt
```

**Extra info**
`WP-CLI version:    0.11.0-alpha` 
```wordpress-importer: 0.6`

**Updated the importer**
Ok I saw that I didn't install the wordpress-importer but just kept it at 0.6.
Updated it to wordpress-importer: 0.6.1 and ran the command again.
Everything ok.

So maybe use the new `plugin install wordpress-importer --force` to install this.

**Comment by pixline** [comment]
Maybe it was an importer glitch? It may fail sometimes with some images for apparently unknown reasons.
I'll test it again, missing importer was noticed yesterday #13 and should be fixed soon. 
Thank you for the report!

**Comment by jmslbam** [comment]
No glitch, ran a clean test with no-pre-installed `wordpress-importer` so that it uses `0.6.1` and it still fails to import the attachment.
Guess it can be the WXR file.

```
Processing post #534 ("test-image-landscape-900") (post_type: attachment)
-- 1 of 162
-- Wed, 10 Jul 2013 12:36:03 +0000
Failed to import Media &#8220;test-image-landscape-900&#8221;<br />

Processing post #535 ("test-image-landscape") (post_type: attachment)
-- 2 of 162
-- Wed, 10 Jul 2013 12:36:04 +0000
Failed to import Media &#8220;test-image-landscape&#8221;<br />
```

So I will try running the other WXR files

**Comment by pixline** [comment]
I'll look at my previous test because I really didn't noticed it before. It could be a bug in the import command, though.
